FROM ubuntu:16.04
MAINTAINER SUSHMITHA "shridhar@pdx.edu"
RUN apt-get update -y
RUN apt-get install -y python3-pip python3
COPY . /app
WORKDIR /app
RUN pip3 install -r requirements.txt
EXPOSE 8000
ENTRYPOINT ["python3"]
CMD ["app.py"]
